spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: ${URI}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    activate:
      on-profile: "prod"
mail-sender:
  active: enable
  email: ${EMAIL_SENDER}
  password: ${EMAIL_PASSWORD}
jwt:
  secret: ${SECRET_TOKEN}
server:
  port: 443
  ssl:
    key-store: src\main\resources\keystore.p12
    key-store-password: itquiz
    keyStoreType: PKCS12
    keyAlias: tomcat
security:
  require-ssl: true